[package]
name = "nrlmsise-00-c"
version = "0.1.0"
authors = ["Dylan Wagner <vstrideultimate@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.53.1"
cc = "1.0.52"